---
- name: install and start webserver
  hosts: localhost
  tasks:
    - name: install packages
      dnf:
        name: httpd
        state: latest
    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes
