---
- name: install and start webserver
  hosts: localhost
  tasks:
    - name: install packages
      yum:
        name: httpd
        state: latest
        
    - service:
        name: httpd
        state: started
        enable: yes
